In [3]:
import pandas as pd

neural_df = pd.read_csv("rgb-v5_eval_results.csv")
scobot_df = pd.read_csv("scobots_eval_results.csv")
iscobot_df = pd.read_csv("iscobots_eval_results.csv")
skiing_df = pd.read_csv("skiscobots_eval_results.csv")


iscobot_df = iscobot_df.drop(iscobot_df[(iscobot_df.env == "Skiing" )].index)
iscobot_df[iscobot_df["env"] == "Skiing"].sort_values(by=["reward_mean"])
all_df = pd.concat([neural_df, scobot_df, iscobot_df, skiing_df])
all_df = pd.read_csv("rgb-v4-nn_eval_results.csv")
all_df

,Unnamed: 0,env,variant,train_seed,eval_seed,episodes,reward_mean,reward_std,steps_mean,steps_std
0,0,Seaquest,rgbv4-nn,16,789,5,1864.0,14.966630,2263.8,1.326650
1,1,Seaquest,rgbv4-nn,16,1011,5,1864.0,14.966630,2266.6,1.019804
2,2,Seaquest,rgbv4-nn,16,123,5,1860.0,17.888544,2266.0,2.449490
3,3,Seaquest,rgbv4-nn,16,456,5,1860.0,12.649111,2266.4,2.244994
4,4,Seaquest,rgbv4-nn,0,123,5,1852.0,16.000000,2266.0,2.449490
5,5,Seaquest,rgbv4-nn,0,1011,5,1860.0,17.888544,2266.6,1.019804
6,6,Seaquest,rgbv4-nn,0,456,5,1868.0,16.000000,2266.4,2.244994
7,7,Seaquest,rgbv4-nn,0,789,5,1856.0,19.595919,2263.8,1.326650
8,8,Seaquest,rgbv4-nn,32,123,5,1852.0,9.797959,2266.0,2.449490
9,9,Seaquest,rgbv4-nn,32,456,5,1844.0,8.000000,2266.4,2.244994
10,10,Seaquest,rgbv4-nn,32,1011,5,1848.0,9.797959,2266.6,1.019804
11,11,Seaquest,rgbv4-nn,32,789,5,1852.0,9.797959,2263.8,1.326650
12,12,Kangaroo,rgbv4-nn,32,123,5,1800.0,0.000000,679.8,2.712932
13,13,Kangaroo,rgbv4-nn,32,456,5,1800.0,0.000000,680.2,2.638181
14,14,Kangaroo,rgbv4-nn,32,789,5,1800.0,0.000000,677.6,1.019804
15,15,Kangaroo,rgbv4-nn,32,1011,5,1800.0,0.000000,680.4,1.356466
16,16,Kangaroo,rgbv4-nn,0,789,5,1840.0,80.000000,690.4,25.318768
17,17,Kangaroo,rgbv4-nn,0,123,5,1800.0,0.000000,679.8,2.712932
18,18,Kangaroo,rgbv4-nn,0,456,5,1840.0,80.000000,693.0,26.130442
19,19,Kangaroo,rgbv4-nn,0,1011,5,1800.0,0.000000,680.4,1.356466
20,20,Kangaroo,rgbv4-nn,16,789,5,1760.0,80.000000,677.6,1.019804
21,21,Kangaroo,rgbv4-nn,16,123,5,1720.0,97.979590,679.8,2.712932
22,22,Kangaroo,rgbv4-nn,16,1011,5,1720.0,97.979590,680.4,1.356466
23,23,Kangaroo,rgbv4-nn,16,456,5,1760.0,80.000000,680.2,2.638181
24,24,Asterix,rgbv4-nn,32,1011,5,6820.0,2651.339400,1380.4,383.827357
25,25,Asterix,rgbv4-nn,32,123,5,7540.0,3175.279500,1455.4,442.681646
26,26,Asterix,rgbv4-nn,32,456,5,8200.0,2619.923600,1611.0,399.440108
27,27,Asterix,rgbv4-nn,32,789,5,8200.0,2619.923600,1608.4,396.777318
28,28,Asterix,rgbv4-nn,0,456,5,13080.0,3072.718800,1652.4,228.210955
29,29,Asterix,rgbv4-nn,0,123,5,15500.0,2670.580600,1818.6,225.276364
30,30,Asterix,rgbv4-nn,0,789,5,13080.0,3072.718800,1649.8,231.269886
31,31,Asterix,rgbv4-nn,0,1011,5,14460.0,3323.010700,1771.4,260.696452
32,32,Asterix,rgbv4-nn,16,456,5,9740.0,3795.576400,1558.2,343.389808
33,33,Asterix,rgbv4-nn,16,123,5,10980.0,3221.428200,1732.0,298.425200
34,34,Asterix,rgbv4-nn,16,789,5,9740.0,3795.576400,1555.6,344.976289
35,35,Asterix,rgbv4-nn,16,1011,5,9220.0,3433.016000,1578.6,356.806166
36,36,Bowling,rgbv4-nn,0,123,5,67.2,11.267653,2133.4,18.478095
37,37,Bowling,rgbv4-nn,0,456,5,68.6,13.169662,2133.4,18.874321
38,38,Bowling,rgbv4-nn,0,789,5,72.4,17.636328,2134.2,18.626862
39,39,Bowling,rgbv4-nn,0,1011,5,65.2,14.400001,2125.8,16.606023
40,40,Bowling,rgbv4-nn,32,123,5,71.6,22.641556,2135.8,29.355749
41,41,Bowling,rgbv4-nn,32,456,5,59.0,24.835459,2122.6,36.274509
42,42,Bowling,rgbv4-nn,32,789,5,63.6,27.637655,2123.0,35.597753
43,43,Bowling,rgbv4-nn,32,1011,5,65.6,29.213694,2119.8,34.335987
44,44,Bowling,rgbv4-nn,16,123,5,30.0,0.000000,2079.6,1.356466
45,45,Bowling,rgbv4-nn,16,789,5,42.6,25.200000,2087.6,15.226293
46,46,Bowling,rgbv4-nn,16,456,5,45.2,30.400000,2087.0,15.530615
47,47,Bowling,rgbv4-nn,16,1011,5,30.0,0.000000,2079.4,1.019804
48,48,Tennis,rgbv4-nn,16,123,5,-1.0,0.000000,26995.4,2.416609
49,49,Tennis,rgbv4-nn,16,456,5,-1.0,0.000000,26996.0,2.529822
50,50,Tennis,rgbv4-nn,16,789,5,-1.0,0.000000,26993.4,1.019804
51,51,Tennis,rgbv4-nn,16,1011,5,-1.0,0.000000,26996.2,1.469694

In [4]:
grouped = all_df.groupby(["env", "variant"])

agg_df = grouped["reward_mean"].agg(["mean", "std"])
agg_df

                           mean          std
env      variant
Asterix  rgbv4-nn  10546.666667  2858.420840
Bowling  rgbv4-nn     56.750000    15.613310
Kangaroo rgbv4-nn   1786.666667    39.389277
Seaquest rgbv4-nn   1856.666667     7.202693
Tennis   rgbv4-nn     -1.000000     0.000000

In [5]:
#agg_df.index = agg_df.index.set_levels(agg_df.index.levels[1].str.replace('rgbv5', 'neural'), level=1)
#agg_df.to_csv("agg_results.csv")